### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by galleon** [fteicht/ppddl-planner#1]
See error message:

mv -f src/algorithms/.deps/libppddl_planner_la-symbolic_search.Tpo src/algorithms/.deps/libppddl_planner_la-symbolic_search.Plo
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -Isrc -Isdk/cudd-2.4.1-ftk/include -Isdk/mdpsim-2.2-ftk/include -Isdk/mdpsim-2.2-ftk/include/mdpsim  -O3 -DNDEBUG -MT src/planners/libppddl_planner_la-raw_planner.lo -MD -MP -MF src/planners/.deps/libppddl_planner_la-raw_planner.Tpo -c -o src/planners/libppddl_planner_la-raw_planner.lo `test -f 'src/planners/raw_planner.cc' || echo './'`src/planners/raw_planner.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -Isrc -Isdk/cudd-2.4.1-ftk/include -Isdk/mdpsim-2.2-ftk/include -Isdk/mdpsim-2.2-ftk/include/mdpsim -O3 -DNDEBUG -MT src/planners/libppddl_planner_la-raw_planner.lo -MD -MP -MF src/planners/.deps/libppddl_planner_la-raw_planner.Tpo -c src/planners/raw_planner.cc  -fPIC -DPIC -o src/planners/.libs/libppddl_planner_la-raw_planner.o
src/planners/raw_planner.cc: In member function 'std::pair<const Domain*, const Problem*> RawPlanner::parse_domain_and_problem(const string&, const string&)':
src/planners/raw_planner.cc:109:37: error: 'fopen' was not declared in this scope
     yyin = fopen(domain.c_str(), "r");
                                     ^
src/planners/raw_planner.cc:111:87: error: 'errno' was not declared in this scope
         throw BaseException(std::string("Parsing domain ") + domain + ": " + strerror(errno), "RawPlanner::parse_domain");
                                                                                       ^
src/planners/raw_planner.cc:111:92: error: 'strerror' was not declared in this scope
         throw BaseException(std::string("Parsing domain ") + domain + ": " + strerror(errno), "RawPlanner::parse_domain");
                                                                                            ^
src/planners/raw_planner.cc:115:16: error: 'fclose' was not declared in this scope
     fclose(yyin);
                ^
src/planners/raw_planner.cc:132:89: error: 'errno' was not declared in this scope
         throw BaseException(std::string("Parsing problem ") + problem + ": " + strerror(errno), "RawPlanner::parse_domain");
                                                                                         ^
src/planners/raw_planner.cc:132:94: error: 'strerror' was not declared in this scope
         throw BaseException(std::string("Parsing problem ") + problem + ": " + strerror(errno), "RawPlanner::parse_domain");
                                                                                              ^
src/planners/raw_planner.cc: In member function 'std::string RawPlanner::action(const string&)':
src/planners/raw_planner.cc:185:28: error: aggregate 'std::ostringstream oss' has incomplete type and cannot be defined
         std::ostringstream oss;
                            ^
make[1]: *** [src/planners/libppddl_planner_la-raw_planner.lo] Error 1
make[1]: Leaving directory `/home/shared/ppddl-planner'
make: *** [all] Error 2

**Comment by fteicht** [comment]
Bug corrected. I've pushed the correct version on the repo. Thanks!
